//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Schemas {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("ACTCDOC", Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd", IsNullable=false)]
    public partial class ACTCDOCComplexType {
        
        private BCARQComplexType bCARQField;
        
        private SISARQComplexType sISARQField;
        
        private string eSTARQField;
        
        /// <remarks/>
        public BCARQComplexType BCARQ {
            get {
                return this.bCARQField;
            }
            set {
                this.bCARQField = value;
            }
        }
        
        /// <remarks/>
        public SISARQComplexType SISARQ {
            get {
                return this.sISARQField;
            }
            set {
                this.sISARQField = value;
            }
        }
        
        /// <remarks/>
        public string ESTARQ {
            get {
                return this.eSTARQField;
            }
            set {
                this.eSTARQField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class BCARQComplexType {
        
        private string nomArqField;
        
        private string numCtrlEmisField;
        
        private string numCtrlDestOrField;
        
        private string iSPBEmissorField;
        
        private string iSPBDestinatarioField;
        
        private System.DateTime dtHrArqField;
        
        private string sitReqField;
        
        private Grupo_SeqComplexType grupo_SeqField;
        
        private System.DateTime dtRefField;
        
        /// <remarks/>
        public string NomArq {
            get {
                return this.nomArqField;
            }
            set {
                this.nomArqField = value;
            }
        }
        
        /// <remarks/>
        public string NumCtrlEmis {
            get {
                return this.numCtrlEmisField;
            }
            set {
                this.numCtrlEmisField = value;
            }
        }
        
        /// <remarks/>
        public string NumCtrlDestOr {
            get {
                return this.numCtrlDestOrField;
            }
            set {
                this.numCtrlDestOrField = value;
            }
        }
        
        /// <remarks/>
        public string ISPBEmissor {
            get {
                return this.iSPBEmissorField;
            }
            set {
                this.iSPBEmissorField = value;
            }
        }
        
        /// <remarks/>
        public string ISPBDestinatario {
            get {
                return this.iSPBDestinatarioField;
            }
            set {
                this.iSPBDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DtHrArq {
            get {
                return this.dtHrArqField;
            }
            set {
                this.dtHrArqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string SitReq {
            get {
                return this.sitReqField;
            }
            set {
                this.sitReqField = value;
            }
        }
        
        /// <remarks/>
        public Grupo_SeqComplexType Grupo_Seq {
            get {
                return this.grupo_SeqField;
            }
            set {
                this.grupo_SeqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DtRef {
            get {
                return this.dtRefField;
            }
            set {
                this.dtRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class Grupo_SeqComplexType {
        
        private string numSeqField;
        
        private Indr indrContField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string NumSeq {
            get {
                return this.numSeqField;
            }
            set {
                this.numSeqField = value;
            }
        }
        
        /// <remarks/>
        public Indr IndrCont {
            get {
                return this.indrContField;
            }
            set {
                this.indrContField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public enum Indr {
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class ControleIF_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class Grupo_ACTC101RET_PortlddRecsdComplexType {
        
        private CNPJBase_CodErro identdPartAdmdoField;
        
        private ControleIF_CodErro numCtrlIFField;
        
        private Grupo_ACTC10X_IdentdContrtoComplexType grupo_ACTC101RET_IdentdContrtoField;
        
        private Grupo_ACTC_CliComplexType_CodErro grupo_ACTC101RET_CliField;
        
        private Grupo_ACTC10x_PropPortlddComplexType grupo_ACTC101RET_PropPortlddField;
        
        private Grupo_EndCartaPortldd_ComplexType grupo_ACTC101RET_EndCartaPortlddField;
        
        private string codErroField;
        
        /// <remarks/>
        public CNPJBase_CodErro IdentdPartAdmdo {
            get {
                return this.identdPartAdmdoField;
            }
            set {
                this.identdPartAdmdoField = value;
            }
        }
        
        /// <remarks/>
        public ControleIF_CodErro NumCtrlIF {
            get {
                return this.numCtrlIFField;
            }
            set {
                this.numCtrlIFField = value;
            }
        }
        
        /// <remarks/>
        public Grupo_ACTC10X_IdentdContrtoComplexType Grupo_ACTC101RET_IdentdContrto {
            get {
                return this.grupo_ACTC101RET_IdentdContrtoField;
            }
            set {
                this.grupo_ACTC101RET_IdentdContrtoField = value;
            }
        }
        
        /// <remarks/>
        public Grupo_ACTC_CliComplexType_CodErro Grupo_ACTC101RET_Cli {
            get {
                return this.grupo_ACTC101RET_CliField;
            }
            set {
                this.grupo_ACTC101RET_CliField = value;
            }
        }
        
        /// <remarks/>
        public Grupo_ACTC10x_PropPortlddComplexType Grupo_ACTC101RET_PropPortldd {
            get {
                return this.grupo_ACTC101RET_PropPortlddField;
            }
            set {
                this.grupo_ACTC101RET_PropPortlddField = value;
            }
        }
        
        /// <remarks/>
        public Grupo_EndCartaPortldd_ComplexType Grupo_ACTC101RET_EndCartaPortldd {
            get {
                return this.grupo_ACTC101RET_EndCartaPortlddField;
            }
            set {
                this.grupo_ACTC101RET_EndCartaPortlddField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class CNPJBase_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class Grupo_ACTC10X_IdentdContrtoComplexType : Grupo_IdentdContrto_ComplexType {
        
        private TpEnteCons_CodErro tpEnteConsField;
        
        private CNPJ_CodErro cNPJCorrespBancField;
        
        /// <remarks/>
        public TpEnteCons_CodErro TpEnteCons {
            get {
                return this.tpEnteConsField;
            }
            set {
                this.tpEnteConsField = value;
            }
        }
        
        /// <remarks/>
        public CNPJ_CodErro CNPJCorrespBanc {
            get {
                return this.cNPJCorrespBancField;
            }
            set {
                this.cNPJCorrespBancField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class TpEnteCons_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class CNPJ_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Grupo_ACTC10X_IdentdContrtoComplexType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class Grupo_IdentdContrto_ComplexType {
        
        private CodContrtoOr_CodErro codContrtoOrField;
        
        private CNPJBase_CodErro cNPJBase_IFOrContrtoField;
        
        private TpContrto_CodErro tpContrtoField;
        
        private string codErroField;
        
        /// <remarks/>
        public CodContrtoOr_CodErro CodContrtoOr {
            get {
                return this.codContrtoOrField;
            }
            set {
                this.codContrtoOrField = value;
            }
        }
        
        /// <remarks/>
        public CNPJBase_CodErro CNPJBase_IFOrContrto {
            get {
                return this.cNPJBase_IFOrContrtoField;
            }
            set {
                this.cNPJBase_IFOrContrtoField = value;
            }
        }
        
        /// <remarks/>
        public TpContrto_CodErro TpContrto {
            get {
                return this.tpContrtoField;
            }
            set {
                this.tpContrtoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class CodContrtoOr_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class TpContrto_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class Grupo_ACTC_CliComplexType_CodErro {
        
        private TpPessoa_CodErro tpCliField;
        
        private CNPJ_CPF_CodErro cNPJ_CPFCliField;
        
        private Nome_CodErro nomCliField;
        
        private Telefone_CodErro telCliField;
        
        private Email_CodErro emailCliField;
        
        private string codErroField;
        
        /// <remarks/>
        public TpPessoa_CodErro TpCli {
            get {
                return this.tpCliField;
            }
            set {
                this.tpCliField = value;
            }
        }
        
        /// <remarks/>
        public CNPJ_CPF_CodErro CNPJ_CPFCli {
            get {
                return this.cNPJ_CPFCliField;
            }
            set {
                this.cNPJ_CPFCliField = value;
            }
        }
        
        /// <remarks/>
        public Nome_CodErro NomCli {
            get {
                return this.nomCliField;
            }
            set {
                this.nomCliField = value;
            }
        }
        
        /// <remarks/>
        public Telefone_CodErro TelCli {
            get {
                return this.telCliField;
            }
            set {
                this.telCliField = value;
            }
        }
        
        /// <remarks/>
        public Email_CodErro EmailCli {
            get {
                return this.emailCliField;
            }
            set {
                this.emailCliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class TpPessoa_CodErro {
        
        private string codErroField;
        
        private TpPessoa valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public TpPessoa Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public enum TpPessoa {
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        J,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class CNPJ_CPF_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class Nome_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class Telefone_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class Email_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class Grupo_ACTC10x_PropPortlddComplexType {
        
        private Data_CodErro dtRefSaldDevdrContbField;
        
        private Valor_CodErro vlrSaldDevdrContbField;
        
        private Percentual_CodErro txJurosNomlField;
        
        private Percentual_CodErro txJurosEftField;
        
        private Percentual_CodErro txCETField;
        
        private CodMoeda_CodErro codMoedaField;
        
        private IndRemun_CodErro indRemunField;
        
        private RegmAmtzc_CodErro regmAmtzcField;
        
        private Data_CodErro dtContrOpField;
        
        private Qtd_CodErro qtdTotParclContrtoField;
        
        private Valor_CodErro vlrFaceParclContrtoField;
        
        private Data_CodErro dtVencPrimParclContrtoField;
        
        private Data_CodErro dtVencUltParclContrtoField;
        
        private string codErroField;
        
        /// <remarks/>
        public Data_CodErro DtRefSaldDevdrContb {
            get {
                return this.dtRefSaldDevdrContbField;
            }
            set {
                this.dtRefSaldDevdrContbField = value;
            }
        }
        
        /// <remarks/>
        public Valor_CodErro VlrSaldDevdrContb {
            get {
                return this.vlrSaldDevdrContbField;
            }
            set {
                this.vlrSaldDevdrContbField = value;
            }
        }
        
        /// <remarks/>
        public Percentual_CodErro TxJurosNoml {
            get {
                return this.txJurosNomlField;
            }
            set {
                this.txJurosNomlField = value;
            }
        }
        
        /// <remarks/>
        public Percentual_CodErro TxJurosEft {
            get {
                return this.txJurosEftField;
            }
            set {
                this.txJurosEftField = value;
            }
        }
        
        /// <remarks/>
        public Percentual_CodErro TxCET {
            get {
                return this.txCETField;
            }
            set {
                this.txCETField = value;
            }
        }
        
        /// <remarks/>
        public CodMoeda_CodErro CodMoeda {
            get {
                return this.codMoedaField;
            }
            set {
                this.codMoedaField = value;
            }
        }
        
        /// <remarks/>
        public IndRemun_CodErro IndRemun {
            get {
                return this.indRemunField;
            }
            set {
                this.indRemunField = value;
            }
        }
        
        /// <remarks/>
        public RegmAmtzc_CodErro RegmAmtzc {
            get {
                return this.regmAmtzcField;
            }
            set {
                this.regmAmtzcField = value;
            }
        }
        
        /// <remarks/>
        public Data_CodErro DtContrOp {
            get {
                return this.dtContrOpField;
            }
            set {
                this.dtContrOpField = value;
            }
        }
        
        /// <remarks/>
        public Qtd_CodErro QtdTotParclContrto {
            get {
                return this.qtdTotParclContrtoField;
            }
            set {
                this.qtdTotParclContrtoField = value;
            }
        }
        
        /// <remarks/>
        public Valor_CodErro VlrFaceParclContrto {
            get {
                return this.vlrFaceParclContrtoField;
            }
            set {
                this.vlrFaceParclContrtoField = value;
            }
        }
        
        /// <remarks/>
        public Data_CodErro DtVencPrimParclContrto {
            get {
                return this.dtVencPrimParclContrtoField;
            }
            set {
                this.dtVencPrimParclContrtoField = value;
            }
        }
        
        /// <remarks/>
        public Data_CodErro DtVencUltParclContrto {
            get {
                return this.dtVencUltParclContrtoField;
            }
            set {
                this.dtVencUltParclContrtoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class Data_CodErro {
        
        private string codErroField;
        
        private System.DateTime valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="date")]
        public System.DateTime Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class Valor_CodErro {
        
        private string codErroField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class Percentual_CodErro {
        
        private string codErroField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class CodMoeda_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class IndRemun_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class RegmAmtzc_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class Qtd_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class Grupo_EndCartaPortldd_ComplexType {
        
        private Texto_CodErro logradEndCartaPortlddField;
        
        private Texto_CodErro compEndCartaPortlddField;
        
        private NumEnd_CodErro numEndCartaPortlddField;
        
        private CidEnd_CodErro cidEndCartaPortlddField;
        
        private UF_CodErro uFEndCartaPortlddField;
        
        private CEP_CodErro cEPEndCartaPortlddField;
        
        private string codErroField;
        
        /// <remarks/>
        public Texto_CodErro LogradEndCartaPortldd {
            get {
                return this.logradEndCartaPortlddField;
            }
            set {
                this.logradEndCartaPortlddField = value;
            }
        }
        
        /// <remarks/>
        public Texto_CodErro CompEndCartaPortldd {
            get {
                return this.compEndCartaPortlddField;
            }
            set {
                this.compEndCartaPortlddField = value;
            }
        }
        
        /// <remarks/>
        public NumEnd_CodErro NumEndCartaPortldd {
            get {
                return this.numEndCartaPortlddField;
            }
            set {
                this.numEndCartaPortlddField = value;
            }
        }
        
        /// <remarks/>
        public CidEnd_CodErro CidEndCartaPortldd {
            get {
                return this.cidEndCartaPortlddField;
            }
            set {
                this.cidEndCartaPortlddField = value;
            }
        }
        
        /// <remarks/>
        public UF_CodErro UFEndCartaPortldd {
            get {
                return this.uFEndCartaPortlddField;
            }
            set {
                this.uFEndCartaPortlddField = value;
            }
        }
        
        /// <remarks/>
        public CEP_CodErro CEPEndCartaPortldd {
            get {
                return this.cEPEndCartaPortlddField;
            }
            set {
                this.cEPEndCartaPortlddField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class Texto_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class NumEnd_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class CidEnd_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class UF_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class CEP_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class Grupo_PortlddActo_ComplexType {
        
        private string identdPartAdmdoField;
        
        private string nUPortlddCTCField;
        
        private string numCtrlIFField;
        
        /// <remarks/>
        public string IdentdPartAdmdo {
            get {
                return this.identdPartAdmdoField;
            }
            set {
                this.identdPartAdmdoField = value;
            }
        }
        
        /// <remarks/>
        public string NUPortlddCTC {
            get {
                return this.nUPortlddCTCField;
            }
            set {
                this.nUPortlddCTCField = value;
            }
        }
        
        /// <remarks/>
        public string NumCtrlIF {
            get {
                return this.numCtrlIFField;
            }
            set {
                this.numCtrlIFField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class ACTC101RETComplexType {
        
        private Grupo_PortlddActo_ComplexType[] grupo_ACTC101RET_PortlddActoField;
        
        private Grupo_ACTC101RET_PortlddRecsdComplexType[] grupo_ACTC101RET_PortlddRecsdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC101RET_PortlddActo")]
        public Grupo_PortlddActo_ComplexType[] Grupo_ACTC101RET_PortlddActo {
            get {
                return this.grupo_ACTC101RET_PortlddActoField;
            }
            set {
                this.grupo_ACTC101RET_PortlddActoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC101RET_PortlddRecsd")]
        public Grupo_ACTC101RET_PortlddRecsdComplexType[] Grupo_ACTC101RET_PortlddRecsd {
            get {
                return this.grupo_ACTC101RET_PortlddRecsdField;
            }
            set {
                this.grupo_ACTC101RET_PortlddRecsdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class ACTC101ComplexType {
        
        private Grupo_ACTC101_PortlddComplexType[] grupo_ACTC101_PortlddField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC101_Portldd")]
        public Grupo_ACTC101_PortlddComplexType[] Grupo_ACTC101_Portldd {
            get {
                return this.grupo_ACTC101_PortlddField;
            }
            set {
                this.grupo_ACTC101_PortlddField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class Grupo_ACTC101_PortlddComplexType {
        
        private string identdPartAdmdoField;
        
        private string numCtrlIFField;
        
        private Grupo_ACTC10X_IdentdContrtoComplexType grupo_ACTC101_IdentdContrtoField;
        
        private Grupo_ACTC_CliComplexType_CodErro grupo_ACTC101_CliField;
        
        private Grupo_ACTC10x_PropPortlddComplexType grupo_ACTC101_PropPortlddField;
        
        private Grupo_EndCartaPortldd_ComplexType grupo_ACTC101_EndCartaPortlddField;
        
        /// <remarks/>
        public string IdentdPartAdmdo {
            get {
                return this.identdPartAdmdoField;
            }
            set {
                this.identdPartAdmdoField = value;
            }
        }
        
        /// <remarks/>
        public string NumCtrlIF {
            get {
                return this.numCtrlIFField;
            }
            set {
                this.numCtrlIFField = value;
            }
        }
        
        /// <remarks/>
        public Grupo_ACTC10X_IdentdContrtoComplexType Grupo_ACTC101_IdentdContrto {
            get {
                return this.grupo_ACTC101_IdentdContrtoField;
            }
            set {
                this.grupo_ACTC101_IdentdContrtoField = value;
            }
        }
        
        /// <remarks/>
        public Grupo_ACTC_CliComplexType_CodErro Grupo_ACTC101_Cli {
            get {
                return this.grupo_ACTC101_CliField;
            }
            set {
                this.grupo_ACTC101_CliField = value;
            }
        }
        
        /// <remarks/>
        public Grupo_ACTC10x_PropPortlddComplexType Grupo_ACTC101_PropPortldd {
            get {
                return this.grupo_ACTC101_PropPortlddField;
            }
            set {
                this.grupo_ACTC101_PropPortlddField = value;
            }
        }
        
        /// <remarks/>
        public Grupo_EndCartaPortldd_ComplexType Grupo_ACTC101_EndCartaPortldd {
            get {
                return this.grupo_ACTC101_EndCartaPortlddField;
            }
            set {
                this.grupo_ACTC101_EndCartaPortlddField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC101.xsd")]
    public partial class SISARQComplexType {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACTC101", typeof(ACTC101ComplexType))]
        [System.Xml.Serialization.XmlElementAttribute("ACTC101RET", typeof(ACTC101RETComplexType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
}
